DROP TABLE ROLE;
CREATE SEQUENCE SEQ;
CREATE TABLE ROLE(ID BIGINT DEFAULT NEXT VALUE FOR SEQ NOT NULL NULL_TO_DEFAULT SEQUENCE SEQ,
   NAME VARCHAR(255) NOT NULL);
INSERT INTO ROLE VALUES (1, 'Developer');
INSERT INTO ROLE VALUES (2, 'Product Owner');
INSERT INTO ROLE VALUES (3, 'Tester');
